extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern const GeoLayout castle_grounds_area_3_geo[];
extern const GeoLayout castle_grounds_area_3[];
extern const Collision castle_grounds_area_3_collision[];
extern const MacroObject castle_grounds_area_3_macro_objs[];
extern const GeoLayout castle_grounds_area_2_geo[];
extern const GeoLayout castle_grounds_area_2[];
extern const Collision castle_grounds_area_2_collision[];
extern const MacroObject castle_grounds_area_2_macro_objs[];
extern Lights1 castle_grounds_dl_checkerboard_lights;
extern Lights1 castle_grounds_dl_wooddd_lights;
extern Lights1 castle_grounds_dl_death_lights;
extern Lights1 castle_grounds_dl_black_lights;
extern Lights1 castle_grounds_dl_theman_lights;
extern Lights1 castle_grounds_dl_crowd_ci4_lights;
extern u8 castle_grounds_dl_checkerboard_i8[];
extern u8 castle_grounds_dl_gold_ci4[];
extern u8 castle_grounds_dl_gold_ci4_pal_rgba16[];
extern u8 castle_grounds_dl_woodtopcrate_ci4_ci4[];
extern u8 castle_grounds_dl_woodtopcrate_ci4_ci4_pal_rgba16[];
extern u8 castle_grounds_dl_thang_ci4[];
extern u8 castle_grounds_dl_thang_ci4_pal_rgba16[];
extern u8 castle_grounds_dl_theman_ci4[];
extern u8 castle_grounds_dl_theman_ci4_pal_rgba16[];
extern u8 castle_grounds_dl_goldbrick_rgba16[];
extern u8 castle_grounds_dl_crowd_texture_ci4[];
extern u8 castle_grounds_dl_crowd_texture_ci4_pal_rgba16[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_0[32];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_1[38];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_2[6];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx castle_grounds_dl_Plane_001_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_001_mesh_layer_1_vtx_0[80];
extern Gfx castle_grounds_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Plane_002_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_002_mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl_Plane_002_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Plane_003_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_003_mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl_Plane_003_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Plane_004_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_004_mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl_Plane_004_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Plane_005_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_005_mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl_Plane_005_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Plane_006_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_006_mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl_Plane_006_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Plane_007_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_007_mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl_Plane_007_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Plane_008_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_008_mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl_Plane_008_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Plane_009_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_009_mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl_Plane_009_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Plane_010_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_010_mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl_Plane_010_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Plane_011_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_011_mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl_Plane_011_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Plane_012_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_012_mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl_Plane_012_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Plane_013_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Plane_013_mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl_Plane_013_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Torus_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Torus_mesh_layer_1_vtx_0[84];
extern Gfx castle_grounds_dl_Torus_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Torus_001_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Torus_001_mesh_layer_1_vtx_0[24];
extern Gfx castle_grounds_dl_Torus_001_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Torus_001_mesh_layer_1_vtx_1[18];
extern Gfx castle_grounds_dl_Torus_001_mesh_layer_1_tri_1[];
extern Gfx mat_castle_grounds_dl_checkerboard[];
extern Gfx mat_revert_castle_grounds_dl_checkerboard[];
extern Gfx mat_castle_grounds_dl_gold[];
extern Gfx mat_revert_castle_grounds_dl_gold[];
extern Gfx mat_castle_grounds_dl_wooddd[];
extern Gfx mat_revert_castle_grounds_dl_wooddd[];
extern Gfx mat_castle_grounds_dl_thank[];
extern Gfx mat_revert_castle_grounds_dl_thank[];
extern Gfx mat_castle_grounds_dl_death[];
extern Gfx mat_castle_grounds_dl_black[];
extern Gfx mat_castle_grounds_dl_theman[];
extern Gfx mat_revert_castle_grounds_dl_theman[];
extern Gfx mat_castle_grounds_dl_goldbrick_ci4[];
extern Gfx mat_revert_castle_grounds_dl_goldbrick_ci4[];
extern Gfx mat_castle_grounds_dl_crowd_ci4[];
extern Gfx mat_revert_castle_grounds_dl_crowd_ci4[];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_001_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_002_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_003_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_004_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_005_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_006_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_007_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_008_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_009_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_010_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_011_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_012_mesh_layer_1[];
extern Gfx castle_grounds_dl_Plane_013_mesh_layer_1[];
extern Gfx castle_grounds_dl_Torus_mesh_layer_1[];
extern Gfx castle_grounds_dl_Torus_001_mesh_layer_1[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
